### ISSUE TITLE
Finalise Qs for artist bios

### ISSUE THREAD

**Issue by evolayak** [SecretDecks/Contentwriting#34]
We should close this asap to send to artists. Do we create a vote on Discord to agree?

https://github.com/SecretDecks/Contentwriting/blob/dbf0ecf76c0ba14bbb2886ac321ca957b7e85858/Artist%20Coordination/Qs%20for%20artist%20bios_template

**Comment by wlstylr** [comment]
The questions look good to me.  What is the format that they will be received by the artist?  Will it be an email, or will we build out something like a typeform?

**Comment by evolayak** [comment]
@sarafanciulli and @tamagit80 - Yeah I think even tomorrow is ok.

@wlstylr - Ideally a typeform or the like. @tamagit80 mentioned an editable PDF. I'll also need include a short intro text for the PDF.

**Comment by DanM3rcurius** [comment]
Comment from Quasar inside Discord:
> Provide pictures, images, or something else as representations of those answers you have.

**Comment by DanM3rcurius** [comment]
I'd suggest to keep the Qs as simple as possible, for example 

### 1st Q
**What's your medium?**
* rationale: some artists are more than one kind of artist or don't have the balls yet to call them selves an artist (some do really struggle with this not only in the beginning)

### 2nd Q
We should give the artist the option to not answer that question; some are maybe also from regions where they're not allowed to do certain art or engage with crypto ledgers. Also move this question to the bottom, as it's optional and less important where an artist is from or living, **or?**

### 3rd Q
**Which of your works has shaped you the most?**
* rationale: *interesting* is an empty word and the above question feels more on point.
* I ask myself: Why we ask this question? To find out about the a work we can tease or understand the artists core, in order to match against cooperative values, **or?**

### 4th Q
**What' your relationship to the Tarot?**
* rationale: the other was two questions in one, so I feel this gives the person only one question and an option to explain as short or long as wanted

### 5th Q
**Is creating Art Your only livelihood?**
* rationale: a bit less personal but offers the same result to us the inquirers: does this person require to sell art to pay for rent and/or food; **or?**

### 7th Q
**Are you at the moment happily working with an art gallery?**
* rationale: fused two questions into one and made it less specific about their personal opinion; if they have a strong one they will voice it here; **or?**

### 8th Q
**What's NFT to you??**
* rationale: shorter question with lots (or little) room for answers.

**Comment by sarafanciulli** [comment]
I find it nice in this way. I only see at question 7 as a bit polemic. Do we really want it? It doesn't add value to content.my opinion

**Comment by evolayak** [comment]
I like these as well, nice refinement. For Question 7 we could leave the "happily..." out. My thought was that we'd take the answers and craft them into a short narrative and off the top of my head I'm not sure how to word an artist's dissatisfaction with a gallery in a chill way.  I also wouldn't want the gallery an artist is working with to come across the bio and be pissed.
